### ISSUE TITLE
merged column headers JSON to TXT

### ISSUE THREAD

**Issue by jrotieno** [sjspielman/phyphy#1]
While converting the HYPHY output JSON files to TXT, the first two column headers get merged.

I use the commands:
`e = phyphy.Extractor("/path/to/file/XX.FUBAR.json")`
`e.extract_csv("XX.FUBAR.txt", delim = "\t")`

The output header comes out like:

> site,alpha	beta	beta-alpha	Prob[alpha>beta]	Prob[alpha<beta]

**Comment by sjspielman** [comment]
This is indeed a bug. I will address it this afternoon, stay tuned!

-Stephanie

**Comment by sjspielman** [comment]
Dear @jrotieno, 

The bug has been fixed in the new release 0.4. Please update to this version, which you can do easily via `pip` (or just download release directly and re-install).

Best, 
Stephanie

**Comment by jrotieno** [comment]
Brilliant, it works okay now. And many thanks for the software!
