### ISSUE TITLE
Using conda installation of HyPhy with phyphy

### ISSUE THREAD

**Issue by flopezo** [sjspielman/phyphy#2]
Hello,

I was wondering if it is possible to use a conda installation of HyPhy with phyphy. I tried the commands below and got the error `.../pkgs/hyphy-2.3.12-0/bin/HYPHYMP: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`.

```
hyphypath = phyphy.HyPhy(install_path = "/path/to/miniconda2/pkgs/hyphy-2.3.12-0/") 
relax_test = phyphy.RELAX(alignment = "/path/to/alignment.fas", 
	tree = "/path/to/treefile.tre", 
	test_label = "Foreground",
	hyphy = hyphypath)
relax_test.run_analysis()
```
However, I don't get any errors about shared libraries when I run a RELAX analysis using HyPhy in interactive mode with the same data.

I would really appreciate any help.

**Comment by sjspielman** [comment]
Hi @flopezo,

I have not tested phyphy with a conda installation but will look into this now. Can you please send also a screen shot, or similar, of how RELAX runs in HyPhy interactive mode?

Edit: I now see that conda hyphy has only been released for Linux, and therefore I unfortunately may not be able to test this for you at this time (I currently only have access to Mac). It will still be helpful for me to see the interactive mode. Something to try in the meantime might be to use the argument `build_path` rather than `install_path`, although I don't necessarily think this will solve the issue. 

Thanks, 
Stephanie

**Comment by flopezo** [comment]
Hi Stephanie,

Thank you for your help. Here is the interactive mode stdout 
[stdout.txt](https://github.com/sjspielman/phyphy/files/2155707/stdout.txt)

I tried using `build_path`, but it didn't work. This was the error message:
```
AssertionError: 
[ERROR]: Build path does not contain a correctly built HyPhy.
```

**Comment by sjspielman** [comment]
What command did you issue to reach the HyPhy prompt? This is the information I'll need. Can you also send output from `which HYPHYMP`? 

I will confer with some of the HyPhy developers as well to get more information about the conda install and how to ensure compatibility, but this may take some time.

**Comment by flopezo** [comment]
The command I used for interactive mode was `HYPHYMP`, and this executable is in conda's bin directory `/path/to/miniconda2/bin/HYPHYMP`. When I don't indicate `install_path = "/path/to/miniconda2/pkgs/hyphy-2.3.12-0/"`, I get a different error:

```
Error:
Could not read batch file '/usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/RELAX.bf'.
Path stack:
	/home/flopezosorio/miniconda2/lib/hyphy/
	/usr/local/lib/hyphy/TemplateBatchFiles/SelectionAnalyses/
Check errors.log for details on execution errors.
```

**Comment by flopezo** [comment]
Hi Stephanie,

I tried setting the path of shared libraries (`export LD_LIBRARY_PATH=/path/to/miniconda2/lib:$LD_LIBRARY_PATH`) before running the Python script and that worked. Now I can use the conda-installed HyPhy with phyphy. 

Thank you!

**Comment by sjspielman** [comment]
Hi @flopezo, 

Glad you worked this out!! I will provide this very helpful information to README/FAQ for future users.

Best, 
Stephanie
