### ISSUE TITLE
Conflicting RELAX results when run interactively or via phyphy

### ISSUE THREAD

**Issue by flopezo** [sjspielman/phyphy#3]
Hi Stephanie,

I'm using `phyphy` to do a RELAX analysis and getting conflicting results. When I run the analysis interactively, the result is evidence for intensification, whereas via `phyphy` the result is evidence for relaxation. I'm confused and was wondering what I might be doing wrong. I used the same input data (tree, alignment, and test branch) in both analyses. Here are the two log files:

[OG0002362.relax-interactive.log](https://github.com/sjspielman/phyphy/files/2177623/OG0002362.relax-interactive.log)
[OG0002362.phyphy-relax.log](https://github.com/sjspielman/phyphy/files/2177651/OG0002362.phyphy-relax.log)

This is the `phyphy` script I used:
```
import sys
import os
import phyphy

aln = sys.argv[1]
hyphyexec = phyphy.HyPhy(install_path = "/home/flopezosorio/nas3/miniconda2/pkgs/hyphy-2.3.12-0/", CPU = 2)
relax_test = phyphy.RELAX(alignment = aln, 
		tree = "/home/flopezosorio/nas3/gdnaseq_analyses/selection_tests/darctica-darenaria_16taxa_4253loci_partition.darctica-fground.treefile", 
		test_label = "Foreground",
		hyphy = hyphyexec)
relax_test.run_analysis()
```

I can send you the alignment and tree if you would like to take a closer look. 

I would really appreciate any help.

**Comment by sjspielman** [comment]
Hi @flopezo, 

This seems to be an actual HyPhy bug, per the other issue you opened [here](https://github.com/veg/hyphy/issues/817). The primary HyPhy developers are currently working on fix, which is going to first appear the HyPhy repository under the `beta` branch. It will hopefully be updated in the released version in the near future (although you may wish to ask them to be sure this fix is also included in the `conda` distribution that I see you are using.

If you continue to experience issues after the RELAX bug is fixed, please go ahead and re-open this issue!

Best, 
Stephanie
