### ISSUE TITLE
Phyphy says Hyphy not built correctly in install path

### ISSUE THREAD

**Issue by jebbd** [sjspielman/phyphy#4]
Hi,

I have looked at the previous issue where fixing the LD_LIBRARY_PATH worked to fix the problem. 
This time it's not working.

I am providing the build_path (have also tried install_path). I get the error that the path does not contain a correctly built HYPHY. 

I can run HYPHY directly from the command line with no issues and the menu prompts with no problems.

This is the line where I define my hyphy instance
myhyphy = phyphy.HyPhy(suppress_log=True,build_path = "/opt/software/hyphy/2.3.13/")

Inside /opt/software/hyphy/2.3.13/ is a bin/ with HYPHYMP and lib/ with more subdirectories.

I have also tried the below set up with no luck. If I only define the executable it gets further but can't find the BatchFiles

myhyphy = phyphy.HyPhy(suppress_log=True,executable = "/opt/software/hyphy/2.3.13/bin/HYPHYMP",install_path = "/opt/software/hyphy/2.3.13/lib/")

Any help is appreciated

**Comment by sjspielman** [comment]
Dear @jebbd, 

Can you please send me the following information:
1. The console output from the command `which HYPHYMP`
2. Your full python script that uses phyphy
3. The exact error messages which occur when you run the script

Once you send this information I should be able to diagnose your issue.

Best, 
Stephanie

**Comment by jebbd** [comment]
Hi Stephanie,

    1. The console output from the command which HYPHYMP
/opt/software/hyphy/2.3.13/bin/HYPHYMP

    Your full python script that uses phyphy
The script is attached. It is very minimal.
[hyphy4sonic.txt](https://github.com/sjspielman/phyphy/files/2260691/hyphy4sonic.txt)
    
    The exact error messages which occur when you run the script
Traceback (most recent call last):
  File "hyphy4sonic.py", line 20, in <module>
    myhyphy = phyphy.HyPhy(suppress_log=True,build_path = "/opt/software/hyphy/2.3.13/")
  File "/home/people/13203991/lib/snakemake/lib/python3.4/site-packages/phyphy/hyphy.py", line 84, in __init__
    assert(os.path.exists(self.libpath)), "\n[ERROR]: Build path does not contain a correctly built HyPhy."
AssertionError: 
[ERROR]: Build path does not contain a correctly built HyPhy.

Thanks for the help

**Comment by sjspielman** [comment]
Hi @jebbd,

Please try this small change, which should resolve your path issue:
```myhyphy = phyphy.HyPhy(suppress_log=True,executable = "/opt/software/hyphy/2.3.13/bin/HYPHYMP",install_path = "/opt/software/hyphy/2.3.13/")```
Note, `install_path` here is given *without* with `lib/`.

Let me know if this works!

Best, 
Stephanie

**Comment by jebbd** [comment]
Hi Stephanie,

The good new is it works with  removing the executable option from your suggestion.
`myhyphy = phyphy.HyPhy(suppress_log=True,install_path = "/opt/software/hyphy/2.3.13/")`

With the executable defined it produces the following error, which is maybe helpful for others in the future.

> Traceback (most recent call last):
>   File "hyphy4sonic.py", line 21, in <module>
>     myhyphy = phyphy.HyPhy(suppress_log=True,executable = "/opt/software/hyphy/2.3.13/bin/HYPHYMP",install_path = "/opt/software/hyphy/2.3.13/")
>   File "/home/people/13203991/lib/snakemake/lib/python3.4/site-packages/phyphy/hyphy.py", line 108, in __init__
>     raise AssertionError("\n[ERROR]: HyPhy executable not found. Please ensure it is properly installed, or in your provided local path.")
> AssertionError: 
> [ERROR]: HyPhy executable not found. Please ensure it is properly installed, or in your provided local path.

But it is working now.
Thanks for the help and quick responses!

**Comment by sjspielman** [comment]
Hi @jebbd, 

Note that the argument `executable` should only be supplied if one wishes to use the MPI version. I appreciate your suggestions and will indicate how to use the `hyphy` module more clearly in the documentation!

Best, 
Stephanie
