### ISSUE TITLE
FUBAR error Posterior estimation method choice

### ISSUE THREAD

**Issue by alexweisberg** [sjspielman/phyphy#5]
I am running a FUBAR analysis using hyphy (v 2.3.14 just compiled from github). While attempting to run FUBAR using the following code:
import phyphy
myhyphy = phyphy.HyPhy(executable   = "HYPHYMP", CPU=24, build_path= "/Software/hyphy-2.3.14")
myfubar = phyphy.FUBAR(hyphy = myhyphy, alignment = "./inputalignment.aln", tree = "./inputtree.tre", output =  "mydataset.FUBAR.json")
myfubar.run_analysis()

I get the error message:
 Number of grid points per dimension (total number is D^2) (permissible range = [5,50], default value = 20, integer): 20
Error:
Not a valid option: '5' passed to Choice List 'Posterior estimation method' using redirected stdin input

Function call stack

▽
1 : Choice List for description with choice list:NO_SKIP. Store result in selection

▽
	Standard input redirect:

▽
		000000000006 : 2000000.0
		000000000007 : 1000000.0
		000000000008 : 100
		000000000009 : 0.5
		-------
2 : fubar.run_settings["method"]=io.SelectAnOption({terms.fubar.methods.MH:"Full Metropolis-Hastings MCMC algorithm (slowest, original 2013 paper implementation)",terms.fubar.methods.CG:"Collapsed Gibbs sampler (intermediate speed)",terms.fubar.methods.VB0:"0-th order Variational Bayes approximations (fastest, recommended default)"},"Posterior estimation method")
	Standard input redirect:
		000000000006 : 2000000.0
		000000000007 : 1000000.0
		000000000008 : 100
		000000000009 : 0.5
		-------
3 : fubar.RunPrompts(fubar.prompts)
	Standard input redirect:
		000000000006 : 2000000.0
		000000000007 : 1000000.0
		000000000008 : 100
		000000000009 : 0.5
		-------

Check errors.log for details on execution errors.

Any ideas? Thanks!

**Comment by alexweisberg** [comment]
Looking through the phyphy code; it looks like a new option for the MCMC search algorithm for FUBAR has been added to hyphy, and phyphy is incorrectly giving it the number of chains (default 5). A new parameter for this option would probably fix it.

**Comment by sjspielman** [comment]
Thanks for this catch! I'll update phyphy shortly to reflect changes in HyPhy, probably in the next 1-2 days. Stay tuned.

**Comment by sjspielman** [comment]
Hi @alexweisberg, 

Please see the new release here that addresses FUBAR compatibility: https://github.com/sjspielman/phyphy/releases/tag/0.4.3

It should also be on PyPI in a couple minutes.

-Stephanie

**Comment by alexweisberg** [comment]
Thank you! I will try this.
