### ISSUE TITLE
Convert to CSV/TSV failed: 'six' package not provided, need to call 'phyphy/Extractor'

### ISSUE THREAD

**Issue by NPalopoli** [sjspielman/phyphy#6]
Hi,

I just installed phyphy into a new python virtualenv with the Python 3.6.4 interpreter from the Anaconda distribution.

I adapted [this tutorial](https://github.com/sjspielman/phyphy#extracting-csvs-from-hyphy-output-json) on how to extract CSV/TSV files from the JSON output of HyPhy (in particular, that of LEISR).

At first I wasn't able to run it, but the following two commands solve the issue and now I have my .csv and .tsv files:

* manually install the 'six' package used by ETE:
pip install six

* explicitly call the Extractor module from the phyphy package:
e = phyphy.Extractor("/path/to/file")

I am wondering if these errors only happened to my installation, or they may be worth fixing/mentioning in the docs.

**Comment by sjspielman** [comment]
Hi @NPalopoli, 

This is actually a general issue with python2 vs python3, and not specific to `phyphy`.  It is easily resolved by simply installing the `six` package, as you have found. 

Best, 
Stephanie
