### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by isabelschober** [sjspielman/phyphy#8]
Hello,

the links to the full documentation seem to be broken. Would it be possible to reupload it somewhere?

Many thanks!!

**Comment by sjspielman** [comment]
Hi @isabelschober , 

Thanks for bringing this to my attention - I no longer have the `sjspielman.org` domain, but you can access all the docs _indefinitely_ here: [https://sjspielman.github.io/phyphy](https://sjspielman.github.io/phyphy). I will update links in the README right now!

-Stephanie
